//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterdisciplinaryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
    }
}
