//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterdisciplinaryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public System.DateTime startTime { get; set; }
        public Nullable<byte> amount { get; set; }
        public Nullable<byte> people { get; set; }
        public int customerID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public int activityID { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
    }
}
